// flow-typed signature: 5b9f2bb53b59eeb83ba7402550960369
// flow-typed version: <<STUB>>/data.task_v^3.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'data.task'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'data.task' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'data.task/lib/index' {
  declare module.exports: any;
}

declare module 'data.task/lib/task' {
  declare module.exports: any;
}

// Filename aliases
declare module 'data.task/lib/index.js' {
  declare module.exports: $Exports<'data.task/lib/index'>;
}
declare module 'data.task/lib/task.js' {
  declare module.exports: $Exports<'data.task/lib/task'>;
}
