// flow-typed signature: 5cdc0dd00a991a89da7584e0043f0936
// flow-typed version: <<STUB>>/date-fp_v^5.0.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'date-fp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'date-fp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'date-fp/build/add' {
  declare module.exports: any;
}

declare module 'date-fp/build/convertTo' {
  declare module.exports: any;
}

declare module 'date-fp/build/date-fp' {
  declare module.exports: any;
}

declare module 'date-fp/build/date-fp.min' {
  declare module.exports: any;
}

declare module 'date-fp/build/diff' {
  declare module.exports: any;
}

declare module 'date-fp/build/equals' {
  declare module.exports: any;
}

declare module 'date-fp/build/format' {
  declare module.exports: any;
}

declare module 'date-fp/build/fromTime' {
  declare module.exports: any;
}

declare module 'date-fp/build/get' {
  declare module.exports: any;
}

declare module 'date-fp/build/helpers/constants' {
  declare module.exports: any;
}

declare module 'date-fp/build/helpers/util' {
  declare module.exports: any;
}

declare module 'date-fp/build/index' {
  declare module.exports: any;
}

declare module 'date-fp/build/isLeapYear' {
  declare module.exports: any;
}

declare module 'date-fp/build/isValid' {
  declare module.exports: any;
}

declare module 'date-fp/build/max' {
  declare module.exports: any;
}

declare module 'date-fp/build/min' {
  declare module.exports: any;
}

declare module 'date-fp/build/of' {
  declare module.exports: any;
}

declare module 'date-fp/build/parse' {
  declare module.exports: any;
}

declare module 'date-fp/build/set' {
  declare module.exports: any;
}

declare module 'date-fp/build/sub' {
  declare module.exports: any;
}

declare module 'date-fp/build/unixTime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'date-fp/build/add.js' {
  declare module.exports: $Exports<'date-fp/build/add'>;
}
declare module 'date-fp/build/convertTo.js' {
  declare module.exports: $Exports<'date-fp/build/convertTo'>;
}
declare module 'date-fp/build/date-fp.js' {
  declare module.exports: $Exports<'date-fp/build/date-fp'>;
}
declare module 'date-fp/build/date-fp.min.js' {
  declare module.exports: $Exports<'date-fp/build/date-fp.min'>;
}
declare module 'date-fp/build/diff.js' {
  declare module.exports: $Exports<'date-fp/build/diff'>;
}
declare module 'date-fp/build/equals.js' {
  declare module.exports: $Exports<'date-fp/build/equals'>;
}
declare module 'date-fp/build/format.js' {
  declare module.exports: $Exports<'date-fp/build/format'>;
}
declare module 'date-fp/build/fromTime.js' {
  declare module.exports: $Exports<'date-fp/build/fromTime'>;
}
declare module 'date-fp/build/get.js' {
  declare module.exports: $Exports<'date-fp/build/get'>;
}
declare module 'date-fp/build/helpers/constants.js' {
  declare module.exports: $Exports<'date-fp/build/helpers/constants'>;
}
declare module 'date-fp/build/helpers/util.js' {
  declare module.exports: $Exports<'date-fp/build/helpers/util'>;
}
declare module 'date-fp/build/index.js' {
  declare module.exports: $Exports<'date-fp/build/index'>;
}
declare module 'date-fp/build/isLeapYear.js' {
  declare module.exports: $Exports<'date-fp/build/isLeapYear'>;
}
declare module 'date-fp/build/isValid.js' {
  declare module.exports: $Exports<'date-fp/build/isValid'>;
}
declare module 'date-fp/build/max.js' {
  declare module.exports: $Exports<'date-fp/build/max'>;
}
declare module 'date-fp/build/min.js' {
  declare module.exports: $Exports<'date-fp/build/min'>;
}
declare module 'date-fp/build/of.js' {
  declare module.exports: $Exports<'date-fp/build/of'>;
}
declare module 'date-fp/build/parse.js' {
  declare module.exports: $Exports<'date-fp/build/parse'>;
}
declare module 'date-fp/build/set.js' {
  declare module.exports: $Exports<'date-fp/build/set'>;
}
declare module 'date-fp/build/sub.js' {
  declare module.exports: $Exports<'date-fp/build/sub'>;
}
declare module 'date-fp/build/unixTime.js' {
  declare module.exports: $Exports<'date-fp/build/unixTime'>;
}
