// flow-typed signature: 1933051e735e3f52aa56c1c71d5ad729
// flow-typed version: <<STUB>>/dynalite_v^1.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dynalite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dynalite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dynalite/actions/batchGetItem' {
  declare module.exports: any;
}

declare module 'dynalite/actions/batchWriteItem' {
  declare module.exports: any;
}

declare module 'dynalite/actions/createTable' {
  declare module.exports: any;
}

declare module 'dynalite/actions/deleteItem' {
  declare module.exports: any;
}

declare module 'dynalite/actions/deleteTable' {
  declare module.exports: any;
}

declare module 'dynalite/actions/describeTable' {
  declare module.exports: any;
}

declare module 'dynalite/actions/getItem' {
  declare module.exports: any;
}

declare module 'dynalite/actions/listTables' {
  declare module.exports: any;
}

declare module 'dynalite/actions/putItem' {
  declare module.exports: any;
}

declare module 'dynalite/actions/query' {
  declare module.exports: any;
}

declare module 'dynalite/actions/scan' {
  declare module.exports: any;
}

declare module 'dynalite/actions/updateItem' {
  declare module.exports: any;
}

declare module 'dynalite/actions/updateTable' {
  declare module.exports: any;
}

declare module 'dynalite/cli' {
  declare module.exports: any;
}

declare module 'dynalite/db/conditionParser' {
  declare module.exports: any;
}

declare module 'dynalite/db/index' {
  declare module.exports: any;
}

declare module 'dynalite/db/projectionParser' {
  declare module.exports: any;
}

declare module 'dynalite/db/updateParser' {
  declare module.exports: any;
}

declare module 'dynalite/validations/batchGetItem' {
  declare module.exports: any;
}

declare module 'dynalite/validations/batchWriteItem' {
  declare module.exports: any;
}

declare module 'dynalite/validations/createTable' {
  declare module.exports: any;
}

declare module 'dynalite/validations/deleteItem' {
  declare module.exports: any;
}

declare module 'dynalite/validations/deleteTable' {
  declare module.exports: any;
}

declare module 'dynalite/validations/describeTable' {
  declare module.exports: any;
}

declare module 'dynalite/validations/getItem' {
  declare module.exports: any;
}

declare module 'dynalite/validations/index' {
  declare module.exports: any;
}

declare module 'dynalite/validations/listTables' {
  declare module.exports: any;
}

declare module 'dynalite/validations/putItem' {
  declare module.exports: any;
}

declare module 'dynalite/validations/query' {
  declare module.exports: any;
}

declare module 'dynalite/validations/scan' {
  declare module.exports: any;
}

declare module 'dynalite/validations/updateItem' {
  declare module.exports: any;
}

declare module 'dynalite/validations/updateTable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dynalite/actions/batchGetItem.js' {
  declare module.exports: $Exports<'dynalite/actions/batchGetItem'>;
}
declare module 'dynalite/actions/batchWriteItem.js' {
  declare module.exports: $Exports<'dynalite/actions/batchWriteItem'>;
}
declare module 'dynalite/actions/createTable.js' {
  declare module.exports: $Exports<'dynalite/actions/createTable'>;
}
declare module 'dynalite/actions/deleteItem.js' {
  declare module.exports: $Exports<'dynalite/actions/deleteItem'>;
}
declare module 'dynalite/actions/deleteTable.js' {
  declare module.exports: $Exports<'dynalite/actions/deleteTable'>;
}
declare module 'dynalite/actions/describeTable.js' {
  declare module.exports: $Exports<'dynalite/actions/describeTable'>;
}
declare module 'dynalite/actions/getItem.js' {
  declare module.exports: $Exports<'dynalite/actions/getItem'>;
}
declare module 'dynalite/actions/listTables.js' {
  declare module.exports: $Exports<'dynalite/actions/listTables'>;
}
declare module 'dynalite/actions/putItem.js' {
  declare module.exports: $Exports<'dynalite/actions/putItem'>;
}
declare module 'dynalite/actions/query.js' {
  declare module.exports: $Exports<'dynalite/actions/query'>;
}
declare module 'dynalite/actions/scan.js' {
  declare module.exports: $Exports<'dynalite/actions/scan'>;
}
declare module 'dynalite/actions/updateItem.js' {
  declare module.exports: $Exports<'dynalite/actions/updateItem'>;
}
declare module 'dynalite/actions/updateTable.js' {
  declare module.exports: $Exports<'dynalite/actions/updateTable'>;
}
declare module 'dynalite/cli.js' {
  declare module.exports: $Exports<'dynalite/cli'>;
}
declare module 'dynalite/db/conditionParser.js' {
  declare module.exports: $Exports<'dynalite/db/conditionParser'>;
}
declare module 'dynalite/db/index.js' {
  declare module.exports: $Exports<'dynalite/db/index'>;
}
declare module 'dynalite/db/projectionParser.js' {
  declare module.exports: $Exports<'dynalite/db/projectionParser'>;
}
declare module 'dynalite/db/updateParser.js' {
  declare module.exports: $Exports<'dynalite/db/updateParser'>;
}
declare module 'dynalite/index' {
  declare module.exports: $Exports<'dynalite'>;
}
declare module 'dynalite/index.js' {
  declare module.exports: $Exports<'dynalite'>;
}
declare module 'dynalite/validations/batchGetItem.js' {
  declare module.exports: $Exports<'dynalite/validations/batchGetItem'>;
}
declare module 'dynalite/validations/batchWriteItem.js' {
  declare module.exports: $Exports<'dynalite/validations/batchWriteItem'>;
}
declare module 'dynalite/validations/createTable.js' {
  declare module.exports: $Exports<'dynalite/validations/createTable'>;
}
declare module 'dynalite/validations/deleteItem.js' {
  declare module.exports: $Exports<'dynalite/validations/deleteItem'>;
}
declare module 'dynalite/validations/deleteTable.js' {
  declare module.exports: $Exports<'dynalite/validations/deleteTable'>;
}
declare module 'dynalite/validations/describeTable.js' {
  declare module.exports: $Exports<'dynalite/validations/describeTable'>;
}
declare module 'dynalite/validations/getItem.js' {
  declare module.exports: $Exports<'dynalite/validations/getItem'>;
}
declare module 'dynalite/validations/index.js' {
  declare module.exports: $Exports<'dynalite/validations/index'>;
}
declare module 'dynalite/validations/listTables.js' {
  declare module.exports: $Exports<'dynalite/validations/listTables'>;
}
declare module 'dynalite/validations/putItem.js' {
  declare module.exports: $Exports<'dynalite/validations/putItem'>;
}
declare module 'dynalite/validations/query.js' {
  declare module.exports: $Exports<'dynalite/validations/query'>;
}
declare module 'dynalite/validations/scan.js' {
  declare module.exports: $Exports<'dynalite/validations/scan'>;
}
declare module 'dynalite/validations/updateItem.js' {
  declare module.exports: $Exports<'dynalite/validations/updateItem'>;
}
declare module 'dynalite/validations/updateTable.js' {
  declare module.exports: $Exports<'dynalite/validations/updateTable'>;
}
