// flow-typed signature: 2c72ee14cb1f99b118315fbae0b80dc4
// flow-typed version: <<STUB>>/emailjs_v^1.0.8/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emailjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emailjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emailjs/email' {
  declare module.exports: any;
}

declare module 'emailjs/smtp/client' {
  declare module.exports: any;
}

declare module 'emailjs/smtp/error' {
  declare module.exports: any;
}

declare module 'emailjs/smtp/message' {
  declare module.exports: any;
}

declare module 'emailjs/smtp/response' {
  declare module.exports: any;
}

declare module 'emailjs/smtp/smtp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emailjs/email.js' {
  declare module.exports: $Exports<'emailjs/email'>;
}
declare module 'emailjs/smtp/client.js' {
  declare module.exports: $Exports<'emailjs/smtp/client'>;
}
declare module 'emailjs/smtp/error.js' {
  declare module.exports: $Exports<'emailjs/smtp/error'>;
}
declare module 'emailjs/smtp/message.js' {
  declare module.exports: $Exports<'emailjs/smtp/message'>;
}
declare module 'emailjs/smtp/response.js' {
  declare module.exports: $Exports<'emailjs/smtp/response'>;
}
declare module 'emailjs/smtp/smtp.js' {
  declare module.exports: $Exports<'emailjs/smtp/smtp'>;
}
