// flow-typed signature: dcae94113b90006998db38ef8f022cb5
// flow-typed version: <<STUB>>/mock-aws-s3_v^2.3.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-aws-s3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-aws-s3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-aws-s3/Gruntfile' {
  declare module.exports: any;
}

declare module 'mock-aws-s3/lib/mock' {
  declare module.exports: any;
}

declare module 'mock-aws-s3/test/test' {
  declare module.exports: any;
}

declare module 'mock-aws-s3/test/testBasePath' {
  declare module.exports: any;
}

declare module 'mock-aws-s3/test/testDefaultOptions' {
  declare module.exports: any;
}

declare module 'mock-aws-s3/test/testDefaultOptionsBasePath' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-aws-s3/Gruntfile.js' {
  declare module.exports: $Exports<'mock-aws-s3/Gruntfile'>;
}
declare module 'mock-aws-s3/index' {
  declare module.exports: $Exports<'mock-aws-s3'>;
}
declare module 'mock-aws-s3/index.js' {
  declare module.exports: $Exports<'mock-aws-s3'>;
}
declare module 'mock-aws-s3/lib/mock.js' {
  declare module.exports: $Exports<'mock-aws-s3/lib/mock'>;
}
declare module 'mock-aws-s3/test/test.js' {
  declare module.exports: $Exports<'mock-aws-s3/test/test'>;
}
declare module 'mock-aws-s3/test/testBasePath.js' {
  declare module.exports: $Exports<'mock-aws-s3/test/testBasePath'>;
}
declare module 'mock-aws-s3/test/testDefaultOptions.js' {
  declare module.exports: $Exports<'mock-aws-s3/test/testDefaultOptions'>;
}
declare module 'mock-aws-s3/test/testDefaultOptionsBasePath.js' {
  declare module.exports: $Exports<'mock-aws-s3/test/testDefaultOptionsBasePath'>;
}
