// flow-typed signature: 7a78e76fe3595376f8d14916a0bf8978
// flow-typed version: <<STUB>>/oolon-rethink_v^6.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oolon-rethink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oolon-rethink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oolon-rethink/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oolon-rethink/dist/index.js' {
  declare module.exports: $Exports<'oolon-rethink/dist/index'>;
}
