// flow-typed signature: 23f3fc470d367d84f223812d1570bb02
// flow-typed version: <<STUB>>/passport-cognito_v^0.1.8/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-cognito'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-cognito' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-cognito/lib/index' {
  declare module.exports: any;
}

declare module 'passport-cognito/lib/strategy' {
  declare module.exports: any;
}

declare module 'passport-cognito/test/bootstrap/node' {
  declare module.exports: any;
}

declare module 'passport-cognito/test/package.test' {
  declare module.exports: any;
}

declare module 'passport-cognito/test/strategy.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-cognito/lib/index.js' {
  declare module.exports: $Exports<'passport-cognito/lib/index'>;
}
declare module 'passport-cognito/lib/strategy.js' {
  declare module.exports: $Exports<'passport-cognito/lib/strategy'>;
}
declare module 'passport-cognito/test/bootstrap/node.js' {
  declare module.exports: $Exports<'passport-cognito/test/bootstrap/node'>;
}
declare module 'passport-cognito/test/package.test.js' {
  declare module.exports: $Exports<'passport-cognito/test/package.test'>;
}
declare module 'passport-cognito/test/strategy.test.js' {
  declare module.exports: $Exports<'passport-cognito/test/strategy.test'>;
}
