// flow-typed signature: 82e02a02726e7c9d65ebd32cf014b2b0
// flow-typed version: <<STUB>>/s3rver_v^1.0.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   's3rver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's3rver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 's3rver/bin/s3rver' {
  declare module.exports: any;
}

declare module 's3rver/lib/app' {
  declare module.exports: any;
}

declare module 's3rver/lib/controllers' {
  declare module.exports: any;
}

declare module 's3rver/lib/file-store' {
  declare module.exports: any;
}

declare module 's3rver/lib/index' {
  declare module.exports: any;
}

declare module 's3rver/lib/logger' {
  declare module.exports: any;
}

declare module 's3rver/lib/models/bucket' {
  declare module.exports: any;
}

declare module 's3rver/lib/models/s3-object' {
  declare module.exports: any;
}

declare module 's3rver/lib/utils' {
  declare module.exports: any;
}

declare module 's3rver/lib/xml-template-builder' {
  declare module.exports: any;
}

declare module 's3rver/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 's3rver/bin/s3rver.js' {
  declare module.exports: $Exports<'s3rver/bin/s3rver'>;
}
declare module 's3rver/lib/app.js' {
  declare module.exports: $Exports<'s3rver/lib/app'>;
}
declare module 's3rver/lib/controllers.js' {
  declare module.exports: $Exports<'s3rver/lib/controllers'>;
}
declare module 's3rver/lib/file-store.js' {
  declare module.exports: $Exports<'s3rver/lib/file-store'>;
}
declare module 's3rver/lib/index.js' {
  declare module.exports: $Exports<'s3rver/lib/index'>;
}
declare module 's3rver/lib/logger.js' {
  declare module.exports: $Exports<'s3rver/lib/logger'>;
}
declare module 's3rver/lib/models/bucket.js' {
  declare module.exports: $Exports<'s3rver/lib/models/bucket'>;
}
declare module 's3rver/lib/models/s3-object.js' {
  declare module.exports: $Exports<'s3rver/lib/models/s3-object'>;
}
declare module 's3rver/lib/utils.js' {
  declare module.exports: $Exports<'s3rver/lib/utils'>;
}
declare module 's3rver/lib/xml-template-builder.js' {
  declare module.exports: $Exports<'s3rver/lib/xml-template-builder'>;
}
declare module 's3rver/test/test.js' {
  declare module.exports: $Exports<'s3rver/test/test'>;
}
