// flow-typed signature: 148b132b21b9eba5eb3ffa583d1957bd
// flow-typed version: <<STUB>>/sentia-pnr_v^1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sentia-pnr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sentia-pnr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sentia-pnr/src/client' {
  declare module.exports: any;
}

declare module 'sentia-pnr/src/index' {
  declare module.exports: any;
}

declare module 'sentia-pnr/src/parser' {
  declare module.exports: any;
}

declare module 'sentia-pnr/src/server' {
  declare module.exports: any;
}

declare module 'sentia-pnr/src/socket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sentia-pnr/src/client.js' {
  declare module.exports: $Exports<'sentia-pnr/src/client'>;
}
declare module 'sentia-pnr/src/index.js' {
  declare module.exports: $Exports<'sentia-pnr/src/index'>;
}
declare module 'sentia-pnr/src/parser.js' {
  declare module.exports: $Exports<'sentia-pnr/src/parser'>;
}
declare module 'sentia-pnr/src/server.js' {
  declare module.exports: $Exports<'sentia-pnr/src/server'>;
}
declare module 'sentia-pnr/src/socket.js' {
  declare module.exports: $Exports<'sentia-pnr/src/socket'>;
}
